"""remove price_per_night from rooms

Revision ID: fa23633d9de9
Revises: 3c53388de027
Create Date: 2024-03-19 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa23633d9de9'
down_revision = '3c53388de027'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'price_per_night')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('price_per_night', sa.Float(), nullable=True))
    # ### end Alembic commands ### 